mellow_cs/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('mellow_cs.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^orders/', include('mellow_cs.orders.urls', namespace='orders')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

mellow_cs/mellow_cs/orders/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.core.urlresolvers import reverse, reverse_lazy

from . import views


urlpatterns = [
    # Order patterns
    url(
        regex=r'^$',
        view=views.OrderListView.as_view(),
        name='order_list',
    ),
    url(
        regex=r'^(?P<pk>[\d+-]+)/$',
        view=views.OrderDetailView.as_view(),
        name='order_detail',
    ),
    url(
        regex=r'^~import/$',
        view=views.Foo.as_view(),
        name='order_fetch',
    ),
]

mellow_cs/mellow_cs/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

mellow_cs/mellow_cs/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models


class TimeStampedModel(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

mellow_cs/mellow_cs/orders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from mellow_cs.core.models import TimeStampedModel

# class Product(models.Model):
#     Battery-Pack
#     Fast Charger
#     Front Truck
#     Front Wheels
#     Mellow Board
#     Mellow Board 4x4
#     Mellow Drive
#     Mellow Drive 4x4
#     Mellow Remote


#     FRESHMAN = 'FR'
#     SOPHOMORE = 'SO'
#     JUNIOR = 'JR'
#     SENIOR = 'SR'
#     YEAR_IN_SCHOOL_CHOICES = (
#         (FRESHMAN, 'Freshman'),
#         (SOPHOMORE, 'Sophomore'),
#         (JUNIOR, 'Junior'),
#         (SENIOR, 'Senior'),
#     )


class Order(TimeStampedModel):

    order_nr = models.IntegerField()
    user_email = models.EmailField()
    user_bill_firstname = models.CharField(max_length=250)
    user_bill_lastname = models.CharField(max_length=250)
    order_date = models.DateTimeField()
    order_payment = models.CharField(max_length=250)
    order_total = models.DecimalField(max_digits=7, decimal_places=2)
    voucher_discount = models.DecimalField(
        max_digits=7, decimal_places=2,
        default=0.00
    )
    voucher_nr = models.CharField(blank=True, max_length=250)
    article_nr = models.CharField(blank=True, max_length=250)
    article_title = models.CharField(max_length=250)
    article_quantity = models.IntegerField()
    article_price = models.DecimalField(max_digits=7, decimal_places=2)
    country_title = models.CharField(max_length=250)
    order_delivery_cost = models.DecimalField(max_digits=7, decimal_places=2)
    user_address = models.CharField(max_length=250)
    user_bill_street = models.CharField(max_length=250)
    user_bill_street_nr = models.CharField(max_length=250)
    user_bill_zipcode = models.CharField(max_length=250)
    user_bill_city = models.CharField(max_length=250)
    user_delivery_firstname = models.CharField(blank=True, max_length=250)
    user_delivery_lastname = models.CharField(blank=True, max_length=250)
    user_delivery_street = models.CharField(blank=True, max_length=250)
    user_delivery_street_nr = models.CharField(blank=True, max_length=250)
    user_delivery_zipcode = models.CharField(blank=True, max_length=250)
    user_delivery_city = models.CharField(blank=True, max_length=250)
    status = models.CharField(max_length=250)

    class Meta:
        get_latest_by = 'order_date'
        ordering = ['-order_date']

    def __str__(self):
        return self.user_email

    def get_absolute_url(self):
        return reverse(
            'orders:ororder_detail',
            kwargs={
                'pk': self.pk,
            }
        )

mellow_cs/mellow_cs/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

mellow_cs/mellow_cs/orders/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import (DetailView, ListView, RedirectView,
                                  UpdateView, CreateView, TemplateView)

from django.contrib.auth.mixins import LoginRequiredMixin

from mellow_cs.core.mixins import ImportCsvMixin
from .models import Order
# from .models import Project, Document
# from .forms import (ProjectCreateForm, ProjectUpdateForm, DocumentCreateForm,
#                     DocumentUpdateForm)
# from vales.core.mixins import CheckMembershipMixin, AdminRequiredMixin, ActionMixin


class OrderListView(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        # Fetch the queryset from the parent get_queryset
        queryset = super(OrderListView, self).get_queryset()

        # Get the q GET parameter
        q = self.request.GET.get("q")
        if q:
            # Return a filtered queryset
            order_nr_set = queryset.filter(order_nr__iexact=q)
            email_set = queryset.filter(user_email__icontains=q)
            firstname_set = queryset.filter(user_bill_firstname__icontains=q)
            lastname_set = queryset.filter(user_bill_lastname__icontains=q)
            queryset = order_nr_set | email_set | firstname_set | lastname_set
            return queryset
        # Return the base queryset
        return queryset


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order


class Foo(LoginRequiredMixin, ImportCsvMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('orders:order_list')

mellow_cs/mellow_cs/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

mellow_cs/mellow_cs/templates/orders/order_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ order.order_nr }}{% endblock %}

{% block content %}

<!-- Order details section -->
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h2>{{ order.order_nr }}</h2>
      <h2>{{ order.order_date }}</h2>
      <h2>{{ order.article_title }}</h2>
      <h2>{{ order.order_total }}</h2>
      <h2>{{ order.order_payment }}</h2>
    </div>
    <div class="col-sm-4">
      <h2>{{ order.user_email }}</h2>
      <h2>{{ order.user_bill_firstname }} {{ order.user_bill_lastname }}</h2>
      <h2>{{ order.country_title }}</h2>

    </div>
    <div class="col-sm-4">
      <h2>{{ order.order_nr }}</h2>

    </div>
  </div>
</div>
<!-- End Order details section -->
{% endblock content %}

mellow_cs/mellow_cs/templates/orders/order_list.html
{% extends "base.html" %}
{% load static i18n %}
{% load humanize %}
{% block title %}Orders{% endblock %}

{% block content %}
<div class="container">
  <h2>Orders</h2>

  <!-- Action buttons -->
  <div class="row">

    <div class="col-sm-8">
      <form action="{% url 'orders:order_list' %}" method="GET">
        <input type="text" name="q" />
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div>
    <div class="col-sm-4">
      <a class="btn btn-primary" href="#" role="button">Update Orders</a>
    </div>
    <div class="col-sm-12">
      <a class="btn btn-link" href="{% url 'orders:order_list' %}" role="button">All</a>
      <a class="btn btn-link" href="#" role="button">Latest</a>
    </div>
  </div>
  <!-- End Action buttons -->

  <!-- Order List -->
  {% if order_list.count != 0 %}
    <div id="accordion" role="tablist" aria-multiselectable="true">
      {% for order in order_list %}
        <div class="card">
          <div class="card-header" role="tab" id="heading{{ forloop.counter }}">
            <h5 class="mb-0">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter}}">
                {{ order.order_nr }} | {{ order.article_title }}
              </a>

            </h5>
            {{ order.user_bill_firstname }} {{ order.user_bill_lastname }} bought {{ order.article_title }} {{ order.order_date|naturaltime }}
          </div>

          <div id="collapse{{ forloop.counter }}" class="collapse" role="tabpanel" aria-labelledby="heading{{ forloop.counter }}">
            <div class="card-block">
              <div class="container">
                <div class="row">
                  <div class="col-sm-5">
                    <div class="list-group">
                      <!-- Order number item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Order number</h6>
                        <p class="list-group-item">{{ order.order_nr }}</p>
                      </span>
                      <!-- End Order number item -->
                      <!-- Order date item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Order date</h6>
                        <p class="list-group-item">{{ order.order_date }}</p>
                      </span>
                      <!-- End Order date item -->
                      <!-- Payment details item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Payment details</h6>
                        <p class="list-group-item">
                          Method: {{ order.order_payment }}<br />
                          Status: {{ order.status }}
                        </p>
                      </span>
                      <!-- End Payment details item -->
                      <!-- Order details item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Order details</h6>
                        <p class="list-group-item">
                          Total: {{ order.order_total|intcomma }}€<br />
                          Discount: {{ order.voucher_discount|intcomma }}€<br />
                          Shipping: {{ order.order_delivery_cost|intcomma }}€<br />
                          </p>
                      </span>
                      <!-- End Order details item -->
                      <!-- Product details item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Product details</h6>
                        <p class="list-group-item">
                          {{ order.article_title }} | Qty: {{ order.article_quantity }}<br />
                          Price: {{ order.article_price|intcomma}}€ <br />
                          Serial number:
                        </p>
                      </span>
                      <!--  End Product details item -->
                    </div>
                  </div>
                  <div class="col-sm-5">
                    <div class="list-group">
                      <!-- Name item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Name</h6>
                        <p class="list-group-item">
                          {{ order.user_bill_firstname }} {{ order.user_bill_lastname }}
                        </p>
                      </span>
                      <!-- End Name item -->
                      <!-- Email item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Email</h6>
                        <p class="list-group-item">
                          {{ order.user_email }}
                        </p>
                      </span>
                      <!-- End Email item -->
                      <!-- Billing address item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Billing address</h6>
                        <p class="list-group-item">
                          {{ order.user_bill_street }} {{ order.user_bill_sreet_nr }}<br />
                          {{ order.user_bill_zipcode }} {{order.user_bill_city }}<br />
                          {{ order.country_title }}
                        </p>
                      </span>
                      <!-- End billing address item -->
                      <!-- Shipping address item -->
                      <span class="list-group-item list-group-item-action">
                        <h6 class="list-group-item-heading">Shippping address</h6>
                        <p class="list-group-item">
                          {{ order.user_delivery_firstname }} {{ order.user_delivery_lastname }}
                          {{ order.user_delivery_street }} {{ order.user_delivery_sreet_nr }}<br />
                          {{ order.user_delivery_zipcode }} {{order.user_delivery_city }}<br />
                          {{ order.country_title }}
                        </p>
                      </span>
                      <!-- End shipping address item -->
                    </div>
                  </div>
                  <div class="col-sm-2">
                    <a class="btn btn-link" href="{% url 'orders:order_detail' order.pk %}" role="button">View Order</a>
                    <a class="btn btn-link" href="#" role="button">Update Order</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <h4>Oops, there aren't any orders yet. <a href="#">Fetch orders!</a></h4>
  {% endif %}
  <!-- End Order List -->
</div>
{% endblock content %}